attributes:

  metadata:
    restrictions:
      - condition: "not (cluster:net_provider == 'neutron' and networking_parameters:segmentation_type == 'vlan')"
        message: "Please use Neutron with VLAN segmentation, the only network type supported with Big Switch plugin."

  bcf_mode:
    type: "select"
    weight: 5
    value: "P-Only"
    label: "BCF Fabric Mode"
    description: "Big Cloud Fabric can be deployed in either physical-only or physical+virtual Modes."
    values:
      - data: "P-Only"
        label: "P-Only"
      - data: "P+V"
        label: "P+V"

  bcf_controller_1:
    value: ""
    label: "BCF Controller1"
    description: "BCF Controller' IP address and ports: <ip>:<port>"
    weight: 10
    type: "text"
    regex:
        source: '^(?:\d|1?\d\d|2[0-4]\d|25[0-5])(?:\.(?:\d|1?\d\d|2[0-4]\d|25[0-5])){3}(?:\:(?:(6553[0-5])|(655[0-2]\d)|(65[0-4]\d{2})|(6[0-4]\d{3})|([1-5]\d{4})|([1-9]\d{1,3})|([1-9])))$'
        error: "Invalid IP address and port"

  bcf_controller_2:
    value: ""
    label: "BCF Controller2"
    description: "BCF Controller' IP address and ports: <ip>:<port>"
    weight: 11
    type: "text"
    regex:
        source: '^(?:\d|1?\d\d|2[0-4]\d|25[0-5])(?:\.(?:\d|1?\d\d|2[0-4]\d|25[0-5])){3}(?:\:(?:(6553[0-5])|(655[0-2]\d)|(65[0-4]\d{2})|(6[0-4]\d{3})|([1-5]\d{4})|([1-9]\d{1,3})|([1-9])))$'
        error: "Invalid IP address and port"

  bcf_controller_username:
    value: ""
    label: "BCF Controller Username"
    description: "Username to access BCF controllers"
    weight: 20
    type: "text"

  bcf_controller_password:
    value: ""
    label: "BCF Controller Password"
    description: "Password to access BCF controllers"
    weight: 21
    type: "text"

  openstack_instance_id:
    value: ""
    label: "Openstack Instance ID"
    description: "The Openstack instance ID that is unique within the BCF fabric"
    weight: 30
    type: "text"

  bcf_controller_os_mgmt:
    value: ""
    label: "Openstack Management Tenant Name"
    description: "The tenant that defines Openstack management segments"
    weight: 40
    type: "text"
